application: sutsis
version: redesign
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: ./lib
  static_dir: lib
- url: ./data
  static_dir: data
  expiration: "90d"
- url: ./components
  static_dir: bower_components
- url: ./
  static_files: index.html
  upload: index.html
- url: ./search/.*
  static_files: index.html
  upload: index.html
- url: ./search.js
  static_files: search.js
  upload: search.js
- url: ./worker.js
  static_files: worker.js
  upload: worker.js
- url: ./lujvo.js
  static_files: lujvo.js
  upload: lujvo.js
- url: ./parseXML.html
  static_files: parseXML.html
  upload: parseXML.html
- url: ./webapp.appcache
  static_files: webapp.appcache
  upload: webapp.appcache

# Did you know, favicons are crazy as all hell? Now you do!

- url: ./apple-touch-icon-114x114.png
  static_files: favicons/apple-touch-icon-114x114.png
  upload: favicons/apple-touch-icon-114x114.png
- url: ./apple-touch-icon-120x120.png
  static_files: favicons/apple-touch-icon-120x120.png
  upload: favicons/apple-touch-icon-120x120.png
- url: ./apple-touch-icon-144x144.png
  static_files: favicons/apple-touch-icon-144x144.png
  upload: favicons/apple-touch-icon-144x144.png
- url: ./apple-touch-icon-152x152.png
  static_files: favicons/apple-touch-icon-152x152.png
  upload: favicons/apple-touch-icon-152x152.png
- url: ./apple-touch-icon-180x180.png
  static_files: favicons/apple-touch-icon-180x180.png
  upload: favicons/apple-touch-icon-180x180.png
- url: ./apple-touch-icon-57x57.png
  static_files: favicons/apple-touch-icon-57x57.png
  upload: favicons/apple-touch-icon-57x57.png
- url: ./apple-touch-icon-60x60.png
  static_files: favicons/apple-touch-icon-60x60.png
  upload: favicons/apple-touch-icon-60x60.png
- url: ./apple-touch-icon-72x72.png
  static_files: favicons/apple-touch-icon-72x72.png
  upload: favicons/apple-touch-icon-72x72.png
- url: ./apple-touch-icon-76x76.png
  static_files: favicons/apple-touch-icon-76x76.png
  upload: favicons/apple-touch-icon-76x76.png
- url: ./apple-touch-icon-precomposed.png
  static_files: favicons/apple-touch-icon-precomposed.png
  upload: favicons/apple-touch-icon-precomposed.png
- url: ./apple-touch-icon.png
  static_files: favicons/apple-touch-icon.png
  upload: favicons/apple-touch-icon.png
- url: ./browserconfig.xml
  static_files: favicons/browserconfig.xml
  upload: favicons/browserconfig.xml
- url: ./favicon-160x160.png
  static_files: favicons/favicon-160x160.png
  upload: favicons/favicon-160x160.png
- url: ./favicon-16x16.png
  static_files: favicons/favicon-16x16.png
  upload: favicons/favicon-16x16.png
- url: ./favicon-192x192.png
  static_files: favicons/favicon-192x192.png
  upload: favicons/favicon-192x192.png
- url: ./favicon-32x32.png
  static_files: favicons/favicon-32x32.png
  upload: favicons/favicon-32x32.png
- url: ./favicon-96x96.png
  static_files: favicons/favicon-96x96.png
  upload: favicons/favicon-96x96.png
- url: ./favicon.ico
  static_files: favicons/favicon.ico
  upload: favicons/favicon.ico
- url: ./mstile-144x144.png
  static_files: favicons/mstile-144x144.png
  upload: favicons/mstile-144x144.png
- url: ./mstile-150x150.png
  static_files: favicons/mstile-150x150.png
  upload: favicons/mstile-150x150.png
- url: ./mstile-310x150.png
  static_files: favicons/mstile-310x150.png
  upload: favicons/mstile-310x150.png
- url: ./mstile-310x310.png
  static_files: favicons/mstile-310x310.png
  upload: favicons/mstile-310x310.png
- url: ./mstile-70x70.png
  static_files: favicons/mstile-70x70.png
  upload: favicons/mstile-70x70.png
